development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDISCLOUD_URL"] %>
  # <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: DevcampPortfolio_production
